apiVersion: cloudflare.robkenis.dev/v1alpha1
kind: Tunnel
metadata:
  labels:
    app.kubernetes.io/name: tunnel
    app.kubernetes.io/instance: tunnel-sample
    app.kubernetes.io/part-of: cloudflare-tunnels-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloudflare-tunnels-operator
  name: tunnel-sample
spec:
  # TODO(user): Add fields here
